name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"  # Executa todos os dias à meia-noite
  workflow_dispatch:  # Permite rodar manualmente

jobs:
  generate:
    runs-on: ubuntu-latest
    name: generate snake gif
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Generate the snake animation
        uses: Platane/snk@v3
        with:
          github_user_name: SamSantosidc  # <-- seu nome de usuário GitHub
          outputs: |
            dist/github-contribution-grid-snake.svg
          config: |
            theme: dark
            color_snake: '#FF00F6'
            color_dots: '#000000,#222222,#444444,#666666,#888888'
            background: '#000000'

      - name: Push to GitHub
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
